ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name='cart'
urlpatterns = [

    path('add_to_cart/<slug:p>/',views.addcart,name='add_to_cart'),
    path('cartview',views.cartview,name='cartview'),
    path('removecart/<slug:p>/',views.cart_remove,name='cart_remove'),
    path('cartdelete/<slug:p>/',views.cart_delete,name='cart_delete'),
    path('orderform',views.orderform,name='orderform'),
    path('orderview',views.orderview,name='orderview'),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search',include('search.urls')),
    path('cart',include('cart.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name='search'
urlpatterns = [

    path('',views.searchresults,name='searchresults'),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
app_name='shop'
urlpatterns = [

    path('',views.allprodcat,name='allprodcat'),
    path('product/<slug:p>',views.allproduct,name='allproduct'),
    path('details/<slug:l>',views.details,name='details'),
    path('sign',views.signup,name='signup'),
    path('user_login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout')
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    data_added=models.DateField(auto_now=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=10)
    order_status=models.CharField(max_length=30,default="Pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    no_of_items=models.IntegerField()
    data_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.no_of_items*self.product.price
    def __str__(self):
      return self.user.username



class Account(models.Model):
    acctnumber=models.CharField(max_length=20)
    actype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnumber

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render, redirect
from shop.models import Product
from .models import Cart, Account, Order
from django.contrib.auth.decorators import login_required

@login_required
def addcart(request, p):
    p = Product.objects.get(slug=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, product=p)
        if (cart.quantity < cart.product.stock):
            cart.quantity += 1
            cart.save()
    except Cart.DoesNotExist:

        cart = Cart.objects.create(user=user, product=p, quantity=1)
        cart.save()

    return redirect('cart:cartview')

@login_required
def cartview(request):
    total = 0
    user = request.user
    try:
        cart = Cart.objects.filter(user=user)
        for i in cart:
            total = i.quantity * i.product.price
    except Cart.DoesNotExist:
        pass
    return render(request, 'cart.html', {'cart': cart, 'total': total})


@login_required
def cart_remove(request, p):
    p = Product.objects.get(slug=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')


@login_required
def cart_delete(request, p):
    p = Product.objects.get(slug=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, product=p)
        cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')

@login_required
def orderform(request):
    total = 0
    if (request.method == "POST"):
        address = request.POST['address']
        phone = request.POST['phoneNo']
        acctno = request.POST['AcNo']
        user = request.user
        cart = Cart.objects.filter(user=user)
        for i in cart:
            total += i.quantity * i.product.price
        try:
            ac = Account.objects.get(acctnumber=acctno)
            if (ac.amount >= total):
                ac.amount = ac.amount - total
                ac.save()
                for i in cart:
                    a = Order.objects.create(user=user, product=i.product, address=address, phone=phone, order_status="paid",
                                            no_of_items=i.quantity)
                    a.save()
                    i.product.stock = i.product.stock - i.quantity
                    i.product.save()
                cart.delete()
                msg = "Order placed successfully"
                return render(request, 'orderdetails.html', {'msg': msg})
            else:
                msg = "Insufficient Amount.Cannot place this order"
                return render(request, 'orderdetails.html', {'msg': msg})
        except Account.DoesNotExist:
            msg = "Account number is not valid"
            return render(request, 'orderform.html', {'msg': msg})


    return render(request, 'orderform.html', )

@login_required(login_url='shop.user_login')
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status="paid")
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from django.db.models import Q
from shop.models import Product
def searchresults(request):
    query=""
    products=None
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            products=Product.objects.filter(Q(name__icontains=query)|Q(description__icontains=query))
    return render(request,'search.html',{'products':products,'query':query})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=REM:wght@600&family=Roboto:ital,wght@0,100;0,400;0,500;0,700;0,900;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<div class="container-fluid">
    <header>
    <center>
        <img src="{% static 'image/shopping.jpg' %}" height="100px; width=100px">
    </center><div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MyShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item">All Categories</a></li>
               <li><hr class="dropdown-divider"></li>
              {% for i in links%}
            <li><a class="dropdown-item" href="{% url 'shop:allproduct' i.slug %}">{{i.name}}</a></li>
              {% endfor %}

          </ul>

        </li>
            {% if user.is_authenticated %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>{{count}}</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:signup' %}">Signup</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}
      </ul>
      <form method="POST" class="d-flex" action="{% url 'search:searchresults' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div>

        </header>
{% block content %}
{% endblock%}

<footer>
    <div class="footer">
        <p><i class="fa-solid fa-copyright icon_size"></i>Myshop pvt ltd.All Right Reserve</p>
    </div>
</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% block content %}
{% if not cart %}
<div>
    <h1 class="text-center">Cart is Empty</h1>
    <strong><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></strong>
</div>

{% else %}
<div class="row">
    <h1 class="text-center">SHOPPING CART</h1>
    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr>
                <th colspan="5">CART ITEMS</th>
            </tr>
            {% for i in cart %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
                <td><p>{{i.product.name}}</p></td>
                <td><p><strong>Product Id {{i.product.id}}</strong></p>
                    <p><strong>Unit Price:{{i.product.price}}</strong></p>
                    <p><strong>Quantity:{{i.quantity}}</strong></p>
                </td>
                <td><p>subtotal:{{i.subtotal}}</p></td>
                <td>
                    {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:add_to_cart' i.product.slug %}"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.slug %}"><i class="fa fa-minus-circle" aria-hidden="true"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.slug %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.slug %}"><i class="fa fa-minus-circle" aria-hidden="true"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.slug %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
     <div class="col-sm-6">
        <table class="table table-bordered">
            <tr class="text-center">
                <th colspan="5">CHECK OUT</th>
            </tr>
            <tr class="text-center">
                <td>TOTAL PRICE:{{total}}</td>
            </tr>

        </table>
         <a href="{% url 'cart:orderform' %}" class="btn btn-primary">Place Order</a>
         <a href="{% url 'shop:allprodcat' %}" style="position:absolute;right:20px" class="btn btn-primary">Continue Shopping</a>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  <img src="{% static 'image/ecommerce-banner.jpg' %}" height="450px;"  width="100% right:0;">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
  <h3 class="text-center">Our collection </h3>
  <P style="line-height:2;text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    It has survived not only five centuries, but also the leap into electronic typesetting,remaining essentially unchanged.
    It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>
</div>

<div class="container-fluid mt-4" style=margin-bottom:100px;>
  <div class="row">
    {% for i in c %}
    <div class="col-sm-4">
      <div class="card" style="width: 25rem; height:498px;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:250px;width:100%;">
  <div class="card-body">
    <h3 class="card-title">{{i.name}}</h3>
    <p class="card-text" style="text-align:justify">{{i.description}}</p>
    <a href="{% url 'shop:allproduct' i.slug %}" style="position:relative;left:40%" class="btn btn-primary">PRODUCTS</a>
  </div>
</div>

    </div>
        {% endfor %}
  </div>
</div>


{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-4" style=margin-bottom:100px;>
    <div class="row">
      <div class="col-sm-5">
        <img src="{{l.image.url}}" style="height400x;width:400px;">
      </div>
      <div class="col-sm-5">
        <h3 class="card-title text-uppercase">{{l.name}}</h3>
        <h6>{{l.price}}</h6>
        <h4>Production description</h4>
        <p style="text-indent:80px;text-align:justify;line:height:2;">{{l.description}}</p>
          {% if l.stock <= 0 %}
          <h4>Out of stock</h4>
          {% else %}
        <h4 style="padding-top:10px;">
          <a href="{% url 'cart:add_to_cart' l.slug %}" class="btn btn-primary">Add to cart</a></h4>

          {% endif %}
      </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control" name="username" placeholder="Enter username">
        </div>

        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Enter password">
        <br>
        <div class="text-center">
         <button class="btn btn-outline-primary" type="submit">Login</button>
            </div>
        <br>
</div>





{% endblock %}

ecommerce/templates/orderdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2 class="text-center text-success">{{msg}}</h2>
    <h5 class="text-center text-danger">Thank You...</h5>
    <h5 class="text-center"><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></h5>
</div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
  {% csrf_token %}
<div class="container">
<div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control"  name="address"  placeholder="Enter Address">
</div>
<div class="mb-3">
  <label  class="form-label">phone number</label>
  <input type="text" class="form-control" name="phoneNo" placeholder="Enter phone number">
</div>
<div class="mb-3">
  <label  class="form-label">Account No</label>
  <input type="text" class="form-control" name="AcNo"  placeholder="Enter Account No">
</div>
  <div class="text-center">
  <input type="submit" class="btn btn-outline-primary ">
</div>
  </div>
  </form>
{{msg}}
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="=margin-bottom:100px;">
   <div class="row">
       <h5 class="text-center">Name of the Customer:{{u}}</h5>

       {% for i in o %}
       <div class="col-sm-3 py-3" style="border:2px solid black;">
           <img src="{{i.product.image.url}}" height="150px" width="150px">
       </div>
       <div class="col-sm-7 text-center" style="border:2px solid black">
           Delivery Address:{{i.address}}</br>
           Phone Number:{{i.phone}}</br>
           {{i.product.name}}</br>
           {{i.product.price}}</br>
           Quantity Order:{{i.no_of_items}}</br>
           subtotal={{i.subtotal}}</br>
           <strong class="text-primary">Ordered On {{i.data_added}} </strong></br>
           <strong class="text-success">Delivery Status {{i.delivery_status}}</strong></br>
       </div>
       {% endfor %}
   </div>
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  <img src="{{c.image.url}}" height="450px;"  width="100% right:0;">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
  <h3 class="text-center mb-2">{{c.name}} </h3>
  <P style="line-height:2;text-align:justify;">{{c.description}}</P>
</div>

<div class="container-fluid mt-4" style=margin-bottom:100px;>
  <div class="row">
    {% for i in p %}
    <div class="col-sm-4">
      <div class="card" style="width: 25rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:250px;width:100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
    <p class="card-text  text-center" style="text-align:justify">{{i.price}}</p>
     <a href="{% url 'shop:details' i.slug %}" style="position:relative;left:40%" class="btn btn-primary">DETAILS</a>
  </div>
</div>

    </div>
        {% endfor %}
  </div>
</div>


{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
  <div>
    <h4>You have searched for <span class="text_success">{{query}}</span></h4></div>
</center>

<div class="container-fluid mt-4" style=margin-bottom:100px;>
  <div class="row">
    {% for i in products %}
    <div class="col-sm-4">
      <div class="card" style="width: 25rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:250px;width:100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
    <p class="card-text  text-center" style="text-align:justify">{{i.price}}</p>
     <a href="{% url 'shop:details' i.slug %}" style="position:relative;left:40%" class="btn btn-primary">DETAILS</a>
  </div>
</div>

    </div>


    {% empty %}
    <h6 class="text-center text-danger">Result Not Found</h6>

        {% endfor %}
  </div>
</div>


{% endblock %}

ecommerce/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<form method="POST" class="border border-3 border-primary">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="username" placeholder="Enter username">
</div>
 <div class="mb-3">
  <label class="form-label">Firstname</label>
  <input type="text" class="form-control" name="firstname" placeholder="Enter firstname">
</div>
     <div class="mb-3">
  <label class="form-label">Lastname</label>
  <input type="text" class="form-control" name="lastname" placeholder="Enter lastname">
</div>
     <div class="mb-3">
  <label class="form-label">Email address</label>
  <input type="email" class="form-control" name="email"  placeholder="Enter email">
</div>
     <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="password" placeholder="Enter password">
</div>
    <br>
    <div class="text-center">
  <button type="submit" style="font-size:20px;" class="btn btn-outline-primary">signup</button>
    `</div>
    <br>

</form></div>
{% endblock %}